<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\SqlAccessOrchestrator.Application\SqlAccessOrchestrator.Application.csproj" />
    <ProjectReference Include="..\SqlAccessOrchestrator.Infrastructure\SqlAccessOrchestrator.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>
</Project>
